# Generated by Django 2.0 on 2018-09-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
    ]
